# Generated by Django 4.2.11 on 2024-03-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='comment',
            name='challenge',
            field=models.SlugField(default='insert rating', max_length=200, unique=True),
        ),
    ]
